server:
    port: 8888
encrypt:
    key: ABCDEF
spring:
    security:
        user:
            name: techbruiser
            password: techbruiser
    cloud:
        config:
            server:
                encrypt:
                    enabled: false
                git:
                    uri: https://github.com/hariselvam1991/techbruiser-spring-cloudconfig-wa-tolls
                    search-paths: 
                    - station*
                    repos:
                        perf:
                            pattern: '*/perf'
                            uri: https://github.com/hariselvam1991/techbruiser-spring-cloudconfig-wa-tolls-perf
                            search-paths:
                            - 'station*'